"""add executor_id to document

Revision ID: 6353b95a8ab5
Revises: 7e174515bbda
Create Date: 2026-07-02 14:50:32.429011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6353b95a8ab5'
down_revision = '7e174515bbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('executor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['executor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('executor_id')

    # ### end Alembic commands ###
