"""add price to document items

Revision ID: 92ede14270f8
Revises: 6353b95a8ab5
Create Date: 2026-07-08 10:14:47.706782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ede14270f8'
down_revision = '6353b95a8ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_items', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
